from enum import Enum


class CanMessageTypeIDs(Enum):

    CAN_MESSAGE_TYPE_COMMAND = 0x00
    CAN_MESSAGE_TYPE_RESPONSE = 0x01
    CAN_MESSAGE_TYPE_REFERENCE = 0x02
    CAN_MESSAGE_TYPE_MEASUREMENT = 0x03
    CAN_MESSAGE_TYPE_STATUS = 0x04
    CAN_MESSAGE_TYPE_CONFIG = 0x05
    CAN_MESSAGE_TYPE_SPEC = 0x06
